[package]
name = "saku-py"
version = "0.1.10"
edition = "2021"
readme = "README.md"

[lib]
name = "saku"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.15.1", features = ["extension-module"]}

[dependencies.saku]
version = "*"
path = "../../saku"

[dev-dependencies]
